# Generated by Django 4.0.7 on 2022-10-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditPhoneOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=6)),
                ('has_used', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
